# Generated by Django 4.2.3 on 2024-01-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('end_date', models.CharField(max_length=10, verbose_name='تاریخ پایان')),
                ('season_status', models.CharField(choices=[('H', 'High Season'), ('L', 'Low Season')], default='H', max_length=1, verbose_name='وضعیت')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'ایام پیک',
                'verbose_name_plural': 'ایام پیک',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='high_price',
            field=models.IntegerField(default=0, verbose_name='قیمت پیک'),
        ),
        migrations.AddField(
            model_name='room',
            name='low_price',
            field=models.IntegerField(default=0, verbose_name='قیمت غیر پیک'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('R', 'اتاق'), ('S', 'سوئیت')], default='R', max_length=1, verbose_name='تایپ'),
        ),
        migrations.DeleteModel(
            name='RoomPrice',
        ),
    ]
