# Generated by Django 4.2.3 on 2023-11-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='distance',
            field=models.FloatField(default=0, verbose_name='فاصله تا مکان محبوب'),
        ),
    ]
