# Generated by Django 4.2.3 on 2023-11-15 11:00

from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=hotels.models.room_image_path_154, verbose_name='عکس'),
        ),
    ]
