# Generated by Django 4.2.3 on 2024-01-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_seasonprice_room_high_price_room_low_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد اتاق'),
        ),
    ]
