# Generated by Django 4.2.3 on 2024-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('R', 'اتاق'), ('S', 'سوئیت'), ('SR', 'سوئیت رویال'), ('A1', 'آپارتمان یک خوابه'), ('A2', 'آپارتمان دو خوابه')], default='R', max_length=2, verbose_name='تایپ'),
        ),
    ]
