# Generated by Django 4.2.3 on 2023-11-19 15:52

from django.db import migrations, models
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='location_distance',
            field=models.BooleanField(default=False, verbose_name='دارای مکان محبوب'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=hotels.models.room_image_path_154, verbose_name='عکس اصلی'),
        ),
    ]
