# Generated by Django 4.2.3 on 2023-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_city_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_reserve",
            field=models.BooleanField(default=False, verbose_name="خالی / پر"),
        ),
    ]
