# Generated by Django 4.2.3 on 2023-11-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_room_is_reserve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="enter",
            field=models.CharField(max_length=15, verbose_name="ورود"),
        ),
        migrations.CreateModel(
            name="ReservasionNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=15, verbose_name="شماره رزرواسیون"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                        verbose_name="شماره رزرواسیون",
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره رزرواسیون",
                "verbose_name_plural": "شماره رزرواسیون ها",
            },
        ),
        migrations.AddField(
            model_name="request",
            name="reservasion_number",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.reservasionnumber",
                verbose_name="شماره رزرواسیون",
            ),
        ),
    ]
