# Generated by Django 4.2.3 on 2023-11-09 14:17

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تیتر')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(blank=True, upload_to=blogs.models.room_image_path_154, verbose_name='تصاویر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogcategorymodel', verbose_name='دسته بندی')),
            ],
        ),
    ]
