# Generated by Django 4.2.3 on 2023-08-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_passenger_nid_alter_passenger_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام')),
                ('family', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس')),
                ('nid', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('birthdate', models.CharField(max_length=15, verbose_name='تاریخ تولد')),
                ('reserves', models.ManyToManyField(blank=True, to='main.request', verbose_name='رزرو ها')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعات کاربر',
                'verbose_name_plural': 'اطلاعات کاربران',
            },
        ),
    ]
