# Generated by Django 4.2.3 on 2023-11-15 16:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_path, verbose_name='عکس پروفایل'),
        ),
    ]
