# Generated by Django 4.2.3 on 2023-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hotel_likes_hotel_online_reserve'),
        ('accounts', '0002_alter_user_birthdate_alter_user_nid_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel_likes',
            field=models.ManyToManyField(blank=True, to='main.hotel', verbose_name='هتل های محبوب'),
        ),
    ]
