# Generated by Django 4.2.3 on 2023-08-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_reserve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='needs',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نیازمندی ها'),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=75, verbose_name='نام')),
                ('lastname', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=75, verbose_name='ایمیل')),
                ('phone', models.IntegerField(blank=True, verbose_name='شماره تماس')),
                ('nid', models.IntegerField(verbose_name='کد ملی')),
                ('birthdate', models.CharField(max_length=15, verbose_name='تاریخ تولد')),
                ('reserves', models.ManyToManyField(blank=True, to='main.request', verbose_name='رزرو ها')),
            ],
            options={
                'verbose_name': 'مسافران',
                'verbose_name_plural': 'مسافران',
            },
        ),
    ]
