# Generated by Django 4.2.3 on 2023-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_faname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='آفر ویژه'),
        ),
    ]
