# Generated by Django 4.2.3 on 2023-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_needs_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reserve_time',
            field=models.CharField(default='00:00', max_length=5, verbose_name='زمان رزرو'),
        ),
    ]
