# Generated by Django 4.2.3 on 2023-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_request_reserve_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='nid',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تماس'),
        ),
    ]
