# Generated by Django 4.2.3 on 2023-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hotel_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='کانفرم'),
        ),
    ]
