# Generated by Django 4.2.3 on 2023-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_passenger_nid_alter_passenger_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='لایک ها'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='online_reserve',
            field=models.BooleanField(default=False, verbose_name='رزرو آنلاین'),
        ),
    ]
