# Generated by Django 4.2.3 on 2023-11-02 09:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_hotel_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="gallery",
            field=models.ImageField(
                blank=True,
                upload_to=main.models.room_image_path_550,
                verbose_name="گالری تصاویر",
            ),
        ),
    ]
