# Generated by Django 4.2.3 on 2023-11-02 10:50

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_hotel_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to=main.models.room_image_path_550)),
            ],
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="gallery",
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.hotel"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.image"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="gallery",
            field=models.ManyToManyField(through="main.HotelImage", to="main.image"),
        ),
    ]
