# Generated by Django 4.2.3 on 2023-11-02 11:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_image_remove_hotel_gallery_hotelimage_hotel_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نام تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                upload_to=main.models.room_image_path_550, verbose_name="فایل تصویر"
            ),
        ),
    ]
