# Generated by Django 4.2.3 on 2023-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_image_name_alter_image_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "تصویر", "verbose_name_plural": "تصاویر"},
        ),
        migrations.AddField(
            model_name="hotel",
            name="boroobia_suggest",
            field=models.BooleanField(default=False, verbose_name="پیشنهاد بروبیا"),
        ),
    ]
