# Generated by Django 4.2.3 on 2023-11-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_image_options_hotel_boroobia_suggest"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.image"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.room"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="gallery",
            field=models.ManyToManyField(through="main.RoomImage", to="main.image"),
        ),
    ]
