# Generated by Django 4.2.3 on 2023-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_roomimage_room_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="related",
            field=models.CharField(
                choices=[("H", "هتل"), ("R", "اتاق")],
                default="",
                max_length=10,
                verbose_name="مربوط",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=75, verbose_name="نام آیکون"),
        ),
    ]
