# Generated by Django 4.2.3 on 2023-11-05 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_facility_related_alter_facility_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="reserve_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="تاریخ ثبت رزرو"
            ),
        ),
    ]
