# Generated by Django 4.2.3 on 2023-11-11 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_request_reserve_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="starts",
            new_name="stars",
        ),
    ]
