# Generated by Django 4.2.3 on 2023-11-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_rename_starts_hotel_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="floor",
            field=models.IntegerField(default=0, verbose_name="تعداد طبقه"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="rooms",
            field=models.IntegerField(default=0, verbose_name="تعداد اتاق"),
        ),
    ]
