# Generated by Django 4.2.3 on 2023-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_hotel_floor_hotel_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="terms",
            field=models.TextField(blank=True, verbose_name="قوانین هتل"),
        ),
    ]
